{"name": "test_exitoso", "status": "broken", "statusDetails": {"message": "NameError: name 'USERNAME' is not defined", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"34e690df-64f4-442e-b4b1-1e27bc8c96cf\")>\n\n    def test_exitoso(driver):\n>       username = os.getenv(USERNAME)\nE       NameError: name 'USERNAME' is not defined\n\ntest_login.py:11: NameError"}, "start": 1677012210521, "stop": 1677012210521, "uuid": "a3fdf5d4-6802-4cdf-90c1-7f5cca0760cb", "historyId": "7507257998c3ed03ca162f48358fdfb6", "testCaseId": "a076bf817b686cd40bfe86b363d5841f", "fullName": "DialerAutomationTest.tests.test_login#test_exitoso", "labels": [{"name": "parentSuite", "value": "DialerAutomationTest.tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "GS1714064D01LP"}, {"name": "thread", "value": "36296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "DialerAutomationTest.tests.test_login"}]}