{"name": "test_contraseña_incorrecta", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x000001F21164CC50>\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"c7a4acde-e413-47e5-a089-bfab78af0c35\")>\n\n    @pytest.mark.smoketest\n    def test_contraseña_incorrecta(self, driver):\n        username = os.getenv(\"USERNAME_CAP\")\n        password = \"prueba\"\n>       home_screen = HomeScreen(driver)\nE       TypeError: 'module' object is not callable\n\ntests\\test_login.py:39: TypeError"}, "start": 1677596300274, "stop": 1677596300274, "uuid": "b66fb174-0fd1-4eb7-8a00-b22d6518d0a1", "historyId": "df24dea16fa9d8256fcababb700b27d5", "testCaseId": "888ee164850eb955d2944949db111236", "fullName": "tests.test_login.TestLogin#test_contraseña_incorrecta", "labels": [{"name": "tag", "value": "smoketest"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "GS1726967D01LP"}, {"name": "thread", "value": "23456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}