{"name": "test_exitoso", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x000001F210E7A910>\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"2686cf87-9366-4dc0-b348-95f9f7553609\")>\n\n    @pytest.mark.regression\n    def test_exitoso(self, driver):\n        username = os.getenv(\"USERNAME_CAP\")\n        password = os.getenv(\"PASSWORD_CAP\")\n>       home_screen = HomeScreen(driver)\nE       TypeError: 'module' object is not callable\n\ntests\\test_login.py:17: TypeError"}, "start": 1677596274327, "stop": 1677596274327, "uuid": "9014ff86-94fa-431d-99fc-bbadb0d6e057", "historyId": "61e0449d845a21808e47df428ade844b", "testCaseId": "1a2c9b7fe5a1cb821a82968330f91126", "fullName": "tests.test_login.TestLogin#test_exitoso", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "GS1726967D01LP"}, {"name": "thread", "value": "23456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}