{"name": "test_exitoso", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x00000200423E4350>\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"a05c28ec-7b9e-461c-bfd8-282c4cf896ca\")>\n\n    @pytest.mark.regression\n    def test_exitoso(self, driver):\n        username = os.getenv(\"USERNAME_CAP\")\n        password = os.getenv(\"PASSWORD_CAP\")\n>       home_screen = HomeScreen(driver)\nE       TypeError: 'module' object is not callable\n\ntests\\test_login.py:17: TypeError"}, "start": 1677596339613, "stop": 1677596339614, "uuid": "701638d6-1ffd-4394-9a02-f9be0442eab0", "historyId": "61e0449d845a21808e47df428ade844b", "testCaseId": "1a2c9b7fe5a1cb821a82968330f91126", "fullName": "tests.test_login.TestLogin#test_exitoso", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "GS1726967D01LP"}, {"name": "thread", "value": "25480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}